// define a variable to import the <Verifier> or <renamedVerifier> solidity contract generated by Zokrates

// Test verification with correct proof
// - use the contents from proof.json generated from zokrates steps

let squareVerifier = artifacts.require('SquareVerifier');

let correctProof = require('../../zokrates/code/proof');

contract('TestSquareVerifier', accounts => {

    const account_one = accounts[0];

    beforeEach(async function () { 
            this.contract = await squareVerifier.new({from: account_one});
    })

    it('verification with correct proof',async function(){
        let verified = await this.contract.verifyTx.call(correctProof.proof.a, correctProof.proof.b, correctProof.proof.c, correctProof.inputs, {from:account_one});
        assert.equal(verified,true,"verification is valid");
    })

});